### ISSUE TITLE
Bazel Builds will Fail on Pulling if Using Old Org and Repo Name

### ISSUE THREAD

**Issue by jared-rodgers-figure** [bazel-contrib/toolchains_llvm#254] opened 2024-02-13 16:09 UTC
Issue:
Any workspace file still using: `grailbio/bazel-toolchain` will fail when their repository cache is cleared.

Example:
```
# LLVM toolchain
BAZEL_TOOLCHAIN_TAG = "0.8.2"

BAZEL_TOOLCHAIN_SHA = "0fc3a2b0c9c929920f4bed8f2b446a8274cad41f5ee823fd3faa0d7641f20db0"

http_archive(
    name = "com_grail_bazel_toolchain",
    canonical_id = BAZEL_TOOLCHAIN_TAG,
    sha256 = BAZEL_TOOLCHAIN_SHA,
    strip_prefix = "bazel-toolchain-{tag}".format(tag = BAZEL_TOOLCHAIN_TAG),
    url = "https://github.com/grailbio/bazel-toolchain/archive/refs/tags/{tag}.tar.gz".format(tag = BAZEL_TOOLCHAIN_TAG),
)
```
^ this will fail with the following after clearing repository cache (if you have one)
```
ERROR: An error occurred during the fetch of repository 'com_grail_bazel_toolchain':
   Traceback (most recent call last):
        File "/home/teamcityagent/.cache/bazel/_bazel_teamcityagent/d0e51a7af81b9a534cef621e3a7f4b4a/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.8.2.tar.gz] to /home/teamcityagent/.cache/bazel/_bazel_teamcityagent/d0e51a7af81b9a534cef621e3a7f4b4a/external/com_grail_bazel_toolchain/temp5740723840774007276/0.8.2.tar.gz: Checksum was 3e251524b3e8f3b9ec93848e5267c168424f43b7b554efc983a5291c33d78cde but wanted 0fc3a2b0c9c929920f4bed8f2b446a8274cad41f5ee823fd3faa0d7641f20db0
ERROR: /home/teamcityagent/agent/work/6da88d7122413cf3/WORKSPACE:774:13: fetching http_archive rule //external:com_grail_bazel_toolchain: Traceback (most recent call last):
        File "/home/teamcityagent/.cache/bazel/_bazel_teamcityagent/d0e51a7af81b9a534cef621e3a7f4b4a/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.8.2.tar.gz] to /home/teamcityagent/.cache/bazel/_bazel_teamcityagent/d0e51a7af81b9a534cef621e3a7f4b4a/external/com_grail_bazel_toolchain/temp5740723840774007276/0.8.2.tar.gz: Checksum was 3e251524b3e8f3b9ec93848e5267c168424f43b7b554efc983a5291c33d78cde but wanted 0fc3a2b0c9c929920f4bed8f2b446a8274cad41f5ee823fd3faa0d7641f20db0
ERROR: Error computing the main repository mapping: no such package '@com_grail_bazel_toolchain//toolchain': java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.8.2.tar.gz] to /home/teamcityagent/.cache/bazel/_bazel_teamcityagent/d0e51a7af81b9a534cef621e3a7f4b4a/external/com_grail_bazel_toolchain/temp5740723840774007276/0.8.2.tar.gz: Checksum was 3e251524b3e8f3b9ec93848e5267c168424f43b7b554efc983a5291c33d78cde but wanted 0fc3a2b0c9c929920f4bed8f2b446a8274cad41f5ee823fd3faa0d7641f20db0
```
Solution:
No fix really other than updates to release documentation urls for future users to use the right remote and checksum.

**Comment by bogaczl** [comment] 2024-02-13 16:17
This is related to https://github.com/bazel-contrib/toolchains_llvm/issues/253 I created.

"No fix really other than updates to release documentation urls for future users to use the right remote and checksum."
What is the correct URL and checksum then?

**Comment by jared-rodgers-figure** [comment] 2024-02-13 16:41
For my particular build the old url and checksum was:
https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.8.2.tar.gz
0fc3a2b0c9c929920f4bed8f2b446a8274cad41f5ee823fd3faa0d7641f20db0

New:
https://github.com/bazel-contrib/toolchains_llvm/archive/refs/tags/0.8.2.tar.gz
3e251524b3e8f3b9ec93848e5267c168424f43b7b554efc983a5291c33d78cde

seems like the name change `grailbio/bazel-toolchain` to `bazel-contrib/toolchains_llvm` change impacted the release artifacts.

**Comment by siddharthab** [comment] 2024-02-13 17:33
Marking as duplicate of #253.

**Closed by siddharthab** 2024-02-13 17:33 UTC
