### ISSUE TITLE
Wanted: example usage for host != exec

### ISSUE THREAD

**Issue by anguslees** [bazel-contrib/toolchains_llvm#186] opened 2023-02-07 07:41 UTC
Help, I'm lost in a twisty maze of starlark.  This package offers several tantalising docs/comments saying "if host detection won't work for you, you'll need to do XYZ".  I have been unable to make any of XYZ work 😓.

Bug/doc-request/plea-for-help: I'd really appreciate a clear copy+paste example of using `llvm_toolchain` to define a toolchain for a host != exec remote-build situation.  It _looks_ like all the pieces are there in the starlark, but afaics every way of invoking `llvm_toolchain` always uses the real host os+arch - which won't work for me, and contradicts the "you'll need to do XYZ" comments.

To be clear, I can cross-compile from host->exec using llvm_toolchain just fine.  But I'm looking for a toolchain that will run _on_ my exec platform (and perhaps even cross-compile exec->host).  I have all the relevant sysroots, and experience doing this outside bazel.

Or alternatively, confirm this isn't possible so I can stop trying 😄.

**Comment by siddharthab** [comment] 2023-09-18 17:00
#206 could be related. Sorry for the delay in responding. I don't actively monitor this project anymore.

**Comment by siddharthab** [comment] 2024-03-12 07:42
Closing as a duplicate of #206, where the comments have some copy-paste examples.

**Closed by siddharthab** 2024-03-12 07:42 UTC
